assets/lib/_links.scss
It's not currently used, but could be in future?
Happy to just remove it.
Relates to https://github.com/moneyadviceservice/frontend/pull/891.
=> Make extending from `a` optional.

assets/_all.scss
@JiggyPete @KateWilkinson this should be a tidier way of getting the Yeast styles into other projects such as UC.
If you just add this line to your project stylesheet this will get all of the Yeast partials.
`@import 'yeast/assets/all';`
=> Adding 'all' SCSS file to import all partials

assets/base/_forms.scss
Removes an earlier addition that excludes the clear button in the search bar from displaying a focus style.
Current: 
Updated:
=> [DEV APPROVED] - TP: 7559, Comment: adds focus styles to the clear button on search bar

bower.json
We are trying to use the Bower registry for Yeast so that we can start semantically versioning it - this  PR bumps it to 1.0.0.
Yeast will not appear in the Bower registry as we have set `"private": true,` in the bower.json, and since this is already a public repo that contains only (S)CSS there is no risk putting this in the Bower component registry.
=> Bumping Yeast version to 1.0.0

assets/components/dough_theme/callout/_callout.scss, assets/components/dough_theme/callout/_settings.scss, assets/lib/_variables.scss, bower.json
See [this PR](https://github.com/moneyadviceservice/cms/pull/363) for full explanation of the changes.
This PR specifically adds the CSS to Yeast that styles the new Callout module.
It is made slightly more complicated by the fact that some, but not all of the snippets will have a `<h3>` and some will not (this is markup that is in the CMS, so we don't have template control over it. 
- When there is an `<h3>` we need it to appear as the full-width coloured section at the top. 
- When there is _not_ an `<h3>` we fake this by giving the first `<p>` element a `:before` psuedo-element instead of styling the heading. Hence the `span.callout__icon + p` selector.
=> 7757 - New styles for Callout module

assets/components/dough_theme/callout/_callout.scss, bower.json
In PR #24 I restyled the Callout module. Unfortunately we have used the `.callout` class in some of our tools and we do not want the new styles to cascade down into these.
This PR:
- Keeps some base Callout styles in the `.callout` class that can apply everywhere
- Adds a new silent modifier class `%callout--editorial` for the basic structure of the new article page callouts
- Moves any color theming into the `.callout-tip` and `.callout--tool`modifier classes which extend `%callout--editorial`
For reference, these are callouts:
=> Refactoring Callout CSS for specificity

assets/components/dough_theme/form/_form.scss, bower.json
Removes an unused SCSS extend, that causes deprecation warnings in the current version of SASS-Rails, and errors in future versions.
This will have no effect on the CSS that is generated.
=> Fixing SCSS @extend warning

assets/layout/common/_header.scss
Need to submit this PR once more because on testing it removes the search box at some sizes. 
Now only shows the mobile menu when the global nav is not shown, the search box is unchanged.
=> TP: 7773, Comment: Shows mobile menu button only at smaller width

bower.json
After making a change to Yeast earlier I should have bumped the version (newest changes are not displaying on frontend/uat). This PR makes the change to the version number.
=> TP: 7773, Comment: Bump version of Yeast to 1.2.1

assets/layout/common/_header.scss, bower.json
With the introduction of the Global Nav the behaviour of the search box needs to be modified so that it only functions as a dropdown version when the nav is not displayed. This necessitates some updating to the header layout as below. 
Requires changes in Frontend PR1661: https://github.com/moneyadviceservice/frontend/pull/1661
=> [DEV APPROVED] TP: 7924, Comment: Updates header breakpoints for global nav

assets/components/dough_theme/callout/_callout.scss, bower.json
Required for use across tools on site. 
This change was specifically created for PR279 on mortgage_calculator repo: https://github.com/moneyadviceservice/mortgage_calculator/pull/279
=> [DEV APPROVED] TP: 7934, Comment: Updates style of callout

assets/layout/common/_footer.scss, bower.json
This adds the Plain Language logo (and also updates the Social Sharing figures). There is an associated PR in Frontend: https://github.com/moneyadviceservice/frontend/pull/1713
=> TP: 8107, Comment: Adds Clear English logo and text to footer

bower.json
We are having some trouble with tagging the release where the changes arent present in 1.5.0, so this PR creates a new yeast patch version which only bumps the version and contains no other changes.
=> Bumping version to 1.5.1 to fix a tagging problem

assets/components/dough_theme/_all.scss, assets/components/dough_theme/popup_tip/_all.scss, assets/components/dough_theme/popup_tip/_button.scss, assets/components/dough_theme/popup_tip/_content.scss
This PR adds the MAS theme to the popup tooltip component added to dough in the following PR:
https://github.com/moneyadviceservice/dough/pull/285
=> 8380 tooltip theme

assets/components/dough_theme/callout/_callout.scss, bower.json
[TP Link](https://moneyadviceservice.tpondemand.com/entity/8495)
Part 1 of the Target Process story: Element has insufficient colour contrast of `2.7` (foreground colour: #24afa8, background colour: #ffffff, font size: 16.5pt, font weight: bold).
With this change contrast ratio goes up to `7.94:1`.
Before:
After:
Issue ID: DAC_TECH_Colour_01
=> [DEV APPROVED]Improve contrast between colours in callout icon

bower.json
Versions `1.5.2` and `1.5.3` were tagged in git, but `bower.json` hadn't been updated. This PR updates it to what the current new tag is going to be.
=> [DEV APPROVED] - Bump version to 1.5.4

assets/base/_forms.scss
Tickets: [TP8574](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx?acid=6C17D8319C81AC3D36AFAD64CAE08A28#page=userstory/8279&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&searchPopup=UserStory/8574) [TP8575](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx?acid=6C17D8319C81AC3D36AFAD64CAE08A28#page=userstory/8574&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&searchPopup=UserStory/8575)
When hovering on checkboxes and radio buttons currently there is no real indication to the user that this is happening. 
This PR adds a visual hover style (the same as the focus style) and changes the cursor style. 
N.B. Although this was brought up as part of testing on UC, it is equally applicable cross site so the implementation will …
=> [DEV APPROVED] TP: 8574/5, Comment: Adds better visual cue to users

assets/layout/common/_context_bar.scss, bower.json
**Target Process ticket**
[TP7975](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&searchPopup=userstory/7975)
**Summary**
This is a site-wide issue. We have visually hidden the breadcrumbs at mobile view but these remain accessible to screen-readers, which causes confusion to users of that assistive technology. 
This PR removes the breadcrumbs entirely in the mobile view so the same experience exists for both users and non-users of screen readers. 
**Examples**
The black highlight shows the area that VoiceOver considers active when tabbing through the page, which is the visually hidden breadcrumb on the production site: 
Tabbing now moves the user to the next link: 
**QA / …
=> [DEV APPROVED] TP: 7975, Comment: Removes breadcrumbs from display in mobile view

assets/components/dough_theme/popup_tip/_button.scss, assets/components/dough_theme/popup_tip/_content.scss, bower.json
[TP8647](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=userstory/8479&appConfig=eyJhY2lkIjoiREREN0YzQTYyNjg0NEFCOEQxQkVFM0YwNkVDMjhFRkEifQ==&searchPopup=userstory/8647)
This PR provides the MAS-specific styles for the [Dough Tooltip Helpers](https://github.com/moneyadviceservice/dough/pull/291) in the areas of the site where they are used.
=> [DEV APPROVED]8647 tooltip icon

assets/components/dough_theme/callout/_callout.scss, assets/components/dough_theme/callout/_settings.scss, bower.json
This work adds a `callout--warning` modifier class to yeast. 
This class is being added as part of PR [184](https://github.com/moneyadviceservice/wpcc/pull/184) which adds a threshold callout box to WPCC. 
The ticket for the complete piece of work is: TP [#8618](https://moneyadviceservice.tpondemand.com/entity/8618)
=> Wpcc callout threshold

assets/components/dough_theme/callout/_callout.scss, bower.json
Fixes callout overlap bug by adding a z-index
TP ticket [9129](https://moneyadviceservice.tpondemand.com/entity/9129-links-in-callout-boxes-on-my)
This issue can be found on most of the My Money pages:
https://www.moneyadviceservice.org.uk/en/articles/how-to-switch-gas-and-electricity-supplier
https://www.moneyadviceservice.org.uk/en/articles/how-to-save-if-you-have-a-water-meter
https://www.moneyadviceservice.org.uk/en/articles/how-to-cut-the-cost-of-your-supermarket-shopping
=> [DEV APPROVED] 9129 - Callout link bug

assets/layout/common/_contact_panel.scss, bower.json
[TP10734](https://maps.tpondemand.com/entity/10734-remove-whatsapp-contact-option-from-welsh)
This work updates the small-print text that is found on two fo the panels in the footer when viewing the site in Welsh.  The requirement is to move this text so that it is above the buttons and to make it bold. There is a further requirement to update the content of that text but that is out of the scope fo this work as it is CMS controlled. 
The work is in 2 PRs: 
- This one, that makes the style change to embolden the text and remove from English language rendering of footer. 
- [PR2182](https://github.com/moneyadviceservice/frontend/pull/2182) in Frontend that makes the markup change to alter the position of the elements
Current
Updated
=> [DEV APPROVED] Updates styles to render smallprint bold

assets/layout/common/_covid_banner.scss, bower.json
[TP11363](https://maps.tpondemand.com/entity/11363-sticky-banner-on-mas-website-for)
This work adds a banner to direct users to our articles on Coronavirus. 
There are three PRs that make up the implementation of this component: 
- [PR2201](https://github.com/moneyadviceservice/frontend/pull/2201) in frontend that provides the content and markup for the banner, as well as the Rails functionality to render the component only when this is not recorded in a Cookie as having been previously dismissed, and the reference to the associated Dough component. 
- PR61 in yeast (this PR) that provides the styles for the component, and which will be shared with other repos, such as RAD. 
- [PR338](https://github.com/moneyadviceservice/dough/pull/338) in dough that provides the JavaScript component and …
=> 11363 sticky banner coronavirus info

assets/layout/common/_covid_banner.scss, assets/layout/common/_header.scss, bower.json
[TP11381](https://maps.tpondemand.com/entity/11381-dough-not-initialised-on-some-mas)
There are 2 PRs in this piece of work: 
- [PR2212](https://github.com/moneyadviceservice/frontend/pull/2212) on Frontend 
- PR62 on Yeast (this one)
It makes some small changes to our CSS to deal with issues that have become evident where third party users are loading our "empty template" to create content on the MAS estate.
There are a number of problems on the two tool pages this card caused by the usual MAS JavaScript being blocked and a number of page components break, specifically: 
- The Search Box has no means of clearing the input.
- The Navigation on desktop functions with CSS rather than JavaScript. The JavaScript provides a slightly enhanced experience as well as a number of accessibility …
=> [DEV APPROVED] 11381 js missing
